name: PR Test

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Test
        run: |
          xcodebuild test \
            -scheme clearancekitTests \
            -destination 'platform=macOS'
